import asyncio
import os
import time
import json
import logging
from dotenv import load_dotenv

# early load of .env file
dotenv_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)

from app.services.openai_service import OpenAIService

# Configure logging to output to console
logging.basicConfig(level=logging.INFO)

async def main():
    print("=== STARTING GEMINI RUNTIME VERIFICATION ===")
    
    # 1. Print environment details
    gemini_key = os.getenv("GEMINI_API_KEY")
    vite_key = os.getenv("VITE_GEMINI_API_KEY")
    openai_key = os.getenv("OPENAI_API_KEY")
    
    print(f"OPENAI_API_KEY present: {bool(openai_key)}")
    print(f"GEMINI_API_KEY present: {bool(gemini_key)}")
    print(f"VITE_GEMINI_API_KEY present: {bool(vite_key)}")
    
    # 2. Build preferences payload
    preferences = {
        "destination": "Meghalaya",
        "start_location": "Guwahati",
        "total_days": 5,
        "travelers": 2,
        "budget": 25000.0,
        "comfort_level": "moderate",
        "transport_preference": "fastest",
        "place_types": ["adventure"],
        "allow_international_transit": False
    }
    
    # Initialize OpenAIService
    service = OpenAIService()
    
    # Record request start time
    start_time = time.time()
    print(f"Request Trigger Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(start_time))}")
    
    try:
        # Trigger generation
        itinerary = await service.generate_itinerary(preferences)
        end_time = time.time()
        print(f"Response Received Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(end_time))}")
        print(f"Duration: {end_time - start_time:.2f} seconds")
        
        if itinerary:
            print("\n[SUCCESS] Itinerary generated successfully!")
            
            # Check if it was generated by Gemini or fell back
            print(f"Itinerary keys: {list(itinerary.keys())}")
            
            # Let's print some sample content
            print("\n--- Itinerary Sample Details ---")
            print(f"Destination: {itinerary.get('destination')}")
            print(f"Total Days: {itinerary.get('total_days')}")
            print(f"Budget: {itinerary.get('budget')}")
            
            # Print regions
            regions = itinerary.get("regions", [])
            print(f"Number of regions: {len(regions)}")
            for idx, r in enumerate(regions):
                print(f"  Region {idx+1}: {r.get('region_name')} - {r.get('quick_summary')[:80]}...")
            
            # Print attractions
            attractions = itinerary.get("nearby_attractions", [])
            print(f"Number of attractions: {len(attractions)}")
            for idx, a in enumerate(attractions[:3]):
                print(f"  Attraction {idx+1}: {a.get('name')} - {a.get('summary')}")
            
            # Print transport options
            print(f"Transport preference: {itinerary.get('transport_preference')}")
            print(f"Budget utilization: {itinerary.get('budget_utilization')}")
            
            # Look at destination_image_url
            print(f"Destination Image URL: {itinerary.get('destination_image_url')}")
            
            # Let's write the response to a file for inspect
            with open("gemini_runtime_response.json", "w", encoding="utf-8") as f:
                json.dump(itinerary, f, indent=2)
            print("\nItinerary JSON written to gemini_runtime_response.json")
            
        else:
            print("\n[FAILED] Itinerary generation returned None.")
            
    except Exception as e:
        print(f"\n[ERROR] Exception occurred during generation: {e}")

if __name__ == "__main__":
    asyncio.run(main())
